-- Tier 1 module: table is not auto-generated by Core. This must declare the
-- columns Core manages implicitly (id, created_at, updated_at, and
-- created_by since owner_scoped: true in manifest.yaml) plus the fields
-- declared in manifest.yaml's crud.fields. Core cross-checks this table
-- against the manifest at install/update time (see backend/internal/modules/
-- crud.go's validateCrudTable in modulab-core) and refuses to install on any
-- mismatch.
CREATE TABLE notes (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by TEXT        NOT NULL,
    title      TEXT        NOT NULL,
    body       TEXT        NOT NULL DEFAULT '' -- encrypted: true in the manifest still stores as text (AES-256-GCM ciphertext)
);
